import Head from 'next/head';
import Navbar from '../components/Navbar';
import Sliders from '../components/Sliders';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sliders />
      homepage
    </div>
  )
}
